server:
  port: 8848

spring:
  datasource:
    username: nonameless
    url: jdbc:mysql://112.74.79.124:3306/user?characterEncoding=utf8&useSSL=false&
    password: nonameless
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sicnu.pta.entity.po
  mapper-locations: classpath:dao/*.xml